// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7whceqSclQwwV-Lo-8iSsQKFpOJIIv1U',
    appId: '1:708917613624:web:975b08cff8db214254c2cd',
    messagingSenderId: '708917613624',
    projectId: 'project-cf50f',
    authDomain: 'project-cf50f.firebaseapp.com',
    storageBucket: 'project-cf50f.firebasestorage.app',
    measurementId: 'G-NS01JYDTT7',
    databaseURL: 'https://project-cf50f-default-rtdb.asia-southeast1.firebasedatabase.app', // ADD THIS LINE
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXtLyPAEcprdLA5Zt97mFOD4i9zbqUTpA',
    appId: '1:708917613624:android:12d40453d8872c3a54c2cd',
    messagingSenderId: '708917613624',
    projectId: 'project-cf50f',
    storageBucket: 'project-cf50f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7whceqSclQwwV-Lo-8iSsQKFpOJIIv1U',
    appId: '1:708917613624:web:0857e290afcf073954c2cd',
    messagingSenderId: '708917613624',
    projectId: 'project-cf50f',
    authDomain: 'project-cf50f.firebaseapp.com',
    storageBucket: 'project-cf50f.firebasestorage.app',
    measurementId: 'G-KQ2EX6KBHJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-gnlfmaCoJ1qIHylzQD7pchyRXpOVDQ',
    appId: '1:708917613624:ios:d8a08d7a3636340c54c2cd',
    messagingSenderId: '708917613624',
    projectId: 'project-cf50f',
    storageBucket: 'project-cf50f.firebasestorage.app',
    iosBundleId: 'com.example.skillexchange',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-gnlfmaCoJ1qIHylzQD7pchyRXpOVDQ',
    appId: '1:708917613624:ios:d8a08d7a3636340c54c2cd',
    messagingSenderId: '708917613624',
    projectId: 'project-cf50f',
    storageBucket: 'project-cf50f.firebasestorage.app',
    iosBundleId: 'com.example.skillexchange',
  );

}